//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksClient.AdventureWorksServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrder", Namespace="http://schemas.datacontract.org/2004/07/awsvclib.Contracts")]
    [System.SerializableAttribute()]
    public partial class SalesOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BillToAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FreightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ShipDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShipMethodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShipToAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdventureWorksClient.AdventureWorksServiceReference.SalesOrderStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalDueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillToAddressID {
            get {
                return this.BillToAddressIDField;
            }
            set {
                if ((this.BillToAddressIDField.Equals(value) != true)) {
                    this.BillToAddressIDField = value;
                    this.RaisePropertyChanged("BillToAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Freight {
            get {
                return this.FreightField;
            }
            set {
                if ((this.FreightField.Equals(value) != true)) {
                    this.FreightField = value;
                    this.RaisePropertyChanged("Freight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShipDate {
            get {
                return this.ShipDateField;
            }
            set {
                if ((this.ShipDateField.Equals(value) != true)) {
                    this.ShipDateField = value;
                    this.RaisePropertyChanged("ShipDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipMethodID {
            get {
                return this.ShipMethodIDField;
            }
            set {
                if ((this.ShipMethodIDField.Equals(value) != true)) {
                    this.ShipMethodIDField = value;
                    this.RaisePropertyChanged("ShipMethodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipToAddressID {
            get {
                return this.ShipToAddressIDField;
            }
            set {
                if ((this.ShipToAddressIDField.Equals(value) != true)) {
                    this.ShipToAddressIDField = value;
                    this.RaisePropertyChanged("ShipToAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdventureWorksClient.AdventureWorksServiceReference.SalesOrderStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxAmount {
            get {
                return this.TaxAmountField;
            }
            set {
                if ((this.TaxAmountField.Equals(value) != true)) {
                    this.TaxAmountField = value;
                    this.RaisePropertyChanged("TaxAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDue {
            get {
                return this.TotalDueField;
            }
            set {
                if ((this.TotalDueField.Equals(value) != true)) {
                    this.TotalDueField = value;
                    this.RaisePropertyChanged("TotalDue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderStatus", Namespace="http://schemas.datacontract.org/2004/07/awsvclib.Contracts")]
    public enum SalesOrderStatus : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProcess = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Backordered = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shipped = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderDetails", Namespace="http://schemas.datacontract.org/2004/07/awsvclib.Contracts")]
    [System.SerializableAttribute()]
    public partial class SalesOrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LineTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OrderQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdventureWorksClient.AdventureWorksServiceReference.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ProductImageIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProductListPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProductStandardCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceDiscountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineTotal {
            get {
                return this.LineTotalField;
            }
            set {
                if ((this.LineTotalField.Equals(value) != true)) {
                    this.LineTotalField = value;
                    this.RaisePropertyChanged("LineTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short OrderQuantity {
            get {
                return this.OrderQuantityField;
            }
            set {
                if ((this.OrderQuantityField.Equals(value) != true)) {
                    this.OrderQuantityField = value;
                    this.RaisePropertyChanged("OrderQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdventureWorksClient.AdventureWorksServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductColor {
            get {
                return this.ProductColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductColorField, value) != true)) {
                    this.ProductColorField = value;
                    this.RaisePropertyChanged("ProductColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ProductImageIds {
            get {
                return this.ProductImageIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageIdsField, value) != true)) {
                    this.ProductImageIdsField = value;
                    this.RaisePropertyChanged("ProductImageIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProductListPrice {
            get {
                return this.ProductListPriceField;
            }
            set {
                if ((this.ProductListPriceField.Equals(value) != true)) {
                    this.ProductListPriceField = value;
                    this.RaisePropertyChanged("ProductListPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber {
            get {
                return this.ProductNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNumberField, value) != true)) {
                    this.ProductNumberField = value;
                    this.RaisePropertyChanged("ProductNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProductStandardCost {
            get {
                return this.ProductStandardCostField;
            }
            set {
                if ((this.ProductStandardCostField.Equals(value) != true)) {
                    this.ProductStandardCostField = value;
                    this.RaisePropertyChanged("ProductStandardCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPriceDiscount {
            get {
                return this.UnitPriceDiscountField;
            }
            set {
                if ((this.UnitPriceDiscountField.Equals(value) != true)) {
                    this.UnitPriceDiscountField = value;
                    this.RaisePropertyChanged("UnitPriceDiscount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/awsvclib.Contracts")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ListPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ProductImageIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal StandardCostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ListPrice {
            get {
                return this.ListPriceField;
            }
            set {
                if ((this.ListPriceField.Equals(value) != true)) {
                    this.ListPriceField = value;
                    this.RaisePropertyChanged("ListPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ProductImageIds {
            get {
                return this.ProductImageIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageIdsField, value) != true)) {
                    this.ProductImageIdsField = value;
                    this.RaisePropertyChanged("ProductImageIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber {
            get {
                return this.ProductNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNumberField, value) != true)) {
                    this.ProductNumberField = value;
                    this.RaisePropertyChanged("ProductNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StandardCost {
            get {
                return this.StandardCostField;
            }
            set {
                if ((this.StandardCostField.Equals(value) != true)) {
                    this.StandardCostField = value;
                    this.RaisePropertyChanged("StandardCost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/awsvclib.Contracts")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusinessEntityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusinessEntityID {
            get {
                return this.BusinessEntityIDField;
            }
            set {
                if ((this.BusinessEntityIDField.Equals(value) != true)) {
                    this.BusinessEntityIDField = value;
                    this.RaisePropertyChanged("BusinessEntityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/awsvclib.Contracts")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adventure.works", ConfigurationName="AdventureWorksServiceReference.AdventuresWorks")]
    public interface AdventuresWorks {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetSalesOrders", ReplyAction="http://adventure.works/AdventuresWorks/GetSalesOrdersResponse")]
        AdventureWorksClient.AdventureWorksServiceReference.SalesOrder[] GetSalesOrders(int from, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetSalesOrders", ReplyAction="http://adventure.works/AdventuresWorks/GetSalesOrdersResponse")]
        System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.SalesOrder[]> GetSalesOrdersAsync(int from, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetSalesOrdersCount", ReplyAction="http://adventure.works/AdventuresWorks/GetSalesOrdersCountResponse")]
        int GetSalesOrdersCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetSalesOrdersCount", ReplyAction="http://adventure.works/AdventuresWorks/GetSalesOrdersCountResponse")]
        System.Threading.Tasks.Task<int> GetSalesOrdersCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetSalesOrderDetails", ReplyAction="http://adventure.works/AdventuresWorks/GetSalesOrderDetailsResponse")]
        AdventureWorksClient.AdventureWorksServiceReference.SalesOrderDetails[] GetSalesOrderDetails(int salesOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetSalesOrderDetails", ReplyAction="http://adventure.works/AdventuresWorks/GetSalesOrderDetailsResponse")]
        System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.SalesOrderDetails[]> GetSalesOrderDetailsAsync(int salesOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetPeople", ReplyAction="http://adventure.works/AdventuresWorks/GetPeopleResponse")]
        AdventureWorksClient.AdventureWorksServiceReference.Person[] GetPeople(int from, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetPeople", ReplyAction="http://adventure.works/AdventuresWorks/GetPeopleResponse")]
        System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.Person[]> GetPeopleAsync(int from, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetPeopleCount", ReplyAction="http://adventure.works/AdventuresWorks/GetPeopleCountResponse")]
        int GetPeopleCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetPeopleCount", ReplyAction="http://adventure.works/AdventuresWorks/GetPeopleCountResponse")]
        System.Threading.Tasks.Task<int> GetPeopleCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetAddresses", ReplyAction="http://adventure.works/AdventuresWorks/GetAddressesResponse")]
        AdventureWorksClient.AdventureWorksServiceReference.Address[] GetAddresses(int from, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetAddresses", ReplyAction="http://adventure.works/AdventuresWorks/GetAddressesResponse")]
        System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.Address[]> GetAddressesAsync(int from, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetAddressesCount", ReplyAction="http://adventure.works/AdventuresWorks/GetAddressesCountResponse")]
        int GetAddressesCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetAddressesCount", ReplyAction="http://adventure.works/AdventuresWorks/GetAddressesCountResponse")]
        System.Threading.Tasks.Task<int> GetAddressesCountAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (ProductImageRequest) of message ProductImageRequest does not match the default value (GetProductImage)
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetProductImage", ReplyAction="http://adventure.works/AdventuresWorks/GetProductImageResponse")]
        AdventureWorksClient.AdventureWorksServiceReference.ProductImageMessage GetProductImage(AdventureWorksClient.AdventureWorksServiceReference.ProductImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adventure.works/AdventuresWorks/GetProductImage", ReplyAction="http://adventure.works/AdventuresWorks/GetProductImageResponse")]
        System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.ProductImageMessage> GetProductImageAsync(AdventureWorksClient.AdventureWorksServiceReference.ProductImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductImageRequest", WrapperNamespace="http://adventure.works", IsWrapped=true)]
    public partial class ProductImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adventure.works", Order=0)]
        public int ImageID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adventure.works", Order=1)]
        public bool LargeImage;
        
        public ProductImageRequest() {
        }
        
        public ProductImageRequest(int ImageID, bool LargeImage) {
            this.ImageID = ImageID;
            this.LargeImage = LargeImage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductImageMessage", WrapperNamespace="http://adventure.works", IsWrapped=true)]
    public partial class ProductImageMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://adventure.works")]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adventure.works", Order=0)]
        public System.IO.Stream ImageData;
        
        public ProductImageMessage() {
        }
        
        public ProductImageMessage(string FileName, System.IO.Stream ImageData) {
            this.FileName = FileName;
            this.ImageData = ImageData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdventuresWorksChannel : AdventureWorksClient.AdventureWorksServiceReference.AdventuresWorks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdventuresWorksClient : System.ServiceModel.ClientBase<AdventureWorksClient.AdventureWorksServiceReference.AdventuresWorks>, AdventureWorksClient.AdventureWorksServiceReference.AdventuresWorks {
        
        public AdventuresWorksClient() {
        }
        
        public AdventuresWorksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdventuresWorksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventuresWorksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventuresWorksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdventureWorksClient.AdventureWorksServiceReference.SalesOrder[] GetSalesOrders(int from, int count) {
            return base.Channel.GetSalesOrders(from, count);
        }
        
        public System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.SalesOrder[]> GetSalesOrdersAsync(int from, int count) {
            return base.Channel.GetSalesOrdersAsync(from, count);
        }
        
        public int GetSalesOrdersCount() {
            return base.Channel.GetSalesOrdersCount();
        }
        
        public System.Threading.Tasks.Task<int> GetSalesOrdersCountAsync() {
            return base.Channel.GetSalesOrdersCountAsync();
        }
        
        public AdventureWorksClient.AdventureWorksServiceReference.SalesOrderDetails[] GetSalesOrderDetails(int salesOrderID) {
            return base.Channel.GetSalesOrderDetails(salesOrderID);
        }
        
        public System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.SalesOrderDetails[]> GetSalesOrderDetailsAsync(int salesOrderID) {
            return base.Channel.GetSalesOrderDetailsAsync(salesOrderID);
        }
        
        public AdventureWorksClient.AdventureWorksServiceReference.Person[] GetPeople(int from, int count) {
            return base.Channel.GetPeople(from, count);
        }
        
        public System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.Person[]> GetPeopleAsync(int from, int count) {
            return base.Channel.GetPeopleAsync(from, count);
        }
        
        public int GetPeopleCount() {
            return base.Channel.GetPeopleCount();
        }
        
        public System.Threading.Tasks.Task<int> GetPeopleCountAsync() {
            return base.Channel.GetPeopleCountAsync();
        }
        
        public AdventureWorksClient.AdventureWorksServiceReference.Address[] GetAddresses(int from, int count) {
            return base.Channel.GetAddresses(from, count);
        }
        
        public System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.Address[]> GetAddressesAsync(int from, int count) {
            return base.Channel.GetAddressesAsync(from, count);
        }
        
        public int GetAddressesCount() {
            return base.Channel.GetAddressesCount();
        }
        
        public System.Threading.Tasks.Task<int> GetAddressesCountAsync() {
            return base.Channel.GetAddressesCountAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdventureWorksClient.AdventureWorksServiceReference.ProductImageMessage AdventureWorksClient.AdventureWorksServiceReference.AdventuresWorks.GetProductImage(AdventureWorksClient.AdventureWorksServiceReference.ProductImageRequest request) {
            return base.Channel.GetProductImage(request);
        }
        
        public string GetProductImage(int ImageID, bool LargeImage, out System.IO.Stream ImageData) {
            AdventureWorksClient.AdventureWorksServiceReference.ProductImageRequest inValue = new AdventureWorksClient.AdventureWorksServiceReference.ProductImageRequest();
            inValue.ImageID = ImageID;
            inValue.LargeImage = LargeImage;
            AdventureWorksClient.AdventureWorksServiceReference.ProductImageMessage retVal = ((AdventureWorksClient.AdventureWorksServiceReference.AdventuresWorks)(this)).GetProductImage(inValue);
            ImageData = retVal.ImageData;
            return retVal.FileName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.ProductImageMessage> AdventureWorksClient.AdventureWorksServiceReference.AdventuresWorks.GetProductImageAsync(AdventureWorksClient.AdventureWorksServiceReference.ProductImageRequest request) {
            return base.Channel.GetProductImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdventureWorksClient.AdventureWorksServiceReference.ProductImageMessage> GetProductImageAsync(int ImageID, bool LargeImage) {
            AdventureWorksClient.AdventureWorksServiceReference.ProductImageRequest inValue = new AdventureWorksClient.AdventureWorksServiceReference.ProductImageRequest();
            inValue.ImageID = ImageID;
            inValue.LargeImage = LargeImage;
            return ((AdventureWorksClient.AdventureWorksServiceReference.AdventuresWorks)(this)).GetProductImageAsync(inValue);
        }
    }
}
